pagarme/superbowleto

LICENSE
=> license: add mit

src/config/providers.ts, src/providers/bradesco/index.ts
- Change provider production config to change endpoint based on STAGE variable.
- Add log.
=> provider: change bradesco endpoint config and add log.

README.md
Move from travis-ci.com to travis-ci.org as the repo is now open source.
=> travis: use travis-ci.org

src/functions/database/index.ts, src/lib/credentials/index.ts, src/providers/bradesco/index.ts
Add a .catch to the getCredentials promise chain and fix error handling on Bradesco provider.
=> error-handling: catch errors on credstash and providers

src/providers/bradesco/index.ts, src/providers/development/index.ts, src/providers/index.ts, src/resources/boleto/model.ts, test/functional/boleto/create/bradesco/pending.js, test/functional/boleto/create/bradesco/refused.js, test/functional/boleto/create/bradesco/registered.js, test/functional/boleto/create/development/pending.js, test/functional/boleto/create/development/refused.js, test/functional/boleto/create/development/registered.js
- Add development provider to handle test requests
- Change test/create folder architecture
closes pagarme/superbowleto#213
=> provider: add development provider

src/config/lambda.ts, src/config/sqs.ts, src/resources/boleto/index.ts
Change aws configuration to use Environment Variables.
=> process-boletos: fix AWS credentials

src/providers/development/index.ts, test/functional/boleto/create/development/pending.js, test/functional/boleto/create/development/refused.js, test/functional/boleto/create/development/registered.js
Change amount from provider 'development'
=> provider: change amount from provider 'development'

src/config/lambda.ts, src/config/sqs.ts, src/lib/lambda/index.ts, src/lib/sqs/index.ts, src/resources/boleto/index.ts, src/resources/boleto/lambda.ts, src/resources/boleto/queues.ts
Fix register lambda function name to follow the format
${stage}-superbowleto-register-boleto.
=> lambda: fix register lambda function name

src/resources/boleto/index.ts
Do not send 'boleto' to queue if issuer 'development'
=> sqs: do not send 'boleto' to queue if issuer 'development'

src/resources/boleto/service.ts
=> index: order by id

src/resources/boleto/schema.ts
Allow null on optional schema fields.
Write a brief and explicative description of your pull request. 
=> boleto: allow null on optional fields

src/resources/boleto/index.ts, test/functional/boleto/processBoletosToRegister/registered.js, test/functional/boleto/register/pending.js, test/functional/boleto/register/refused.js, test/functional/boleto/register/registered.js
We were calling invoke method wrong. 
=> lambda: fix lambda invoke method

src/resources/boleto/schema.ts
=> task: allow empty payer value for register

src/database/migrations/20170801000001-change-company-name-boleto.js, src/database/migrations/20170801000002-change-company-document-number-boleto.js, src/resources/boleto/model.ts, src/resources/boleto/schema.ts, test/functional/boleto/create.js
=> boleto: allow null on company fields

src/resources/boleto/schema.ts
=> task: allow empty instructions field

package.json, src/providers/bradesco/formatter.ts, test/unit/providers/bradesco/formatter.js, yarn.lock
Set timezone 'America/Sao_Paulo' to provider Bradesco
=> formatter: set timezone 'America/Sao_Paulo' to provider Bradesco

.github/PULL_REQUEST_TEMPLATE.md
the correct is "comfortable"
Write a brief and explicative description of your pull request. 
=> pr-template: fix content typo

package-lock.json, package.json, src/lib/credentials/index.ts, src/lib/errors/index.ts, src/lib/errors/normalizer.ts, src/providers/bradesco/index.ts, src/resources/boleto/index.ts, src/resources/boleto/model.ts, src/resources/boleto/service.ts, tslint.json
As we were using eslint for linting TypeScript files, this commit introduces tslint to the project
The tslint.json file contains the rules and extends the airbnb style guide adapted for tslint
The `npm run lint` command now run both eslint and tslint
Some variable names weren't changed as they are exported and used in many different files
it closes #208
1. I feel confortable with …
=> lint: add tslint to the project

src/resources/boleto/index.ts
Use bluebird promise on register function so it is possible to use
`.tap` to log.
=> register: use bluebird promise on handler

src/database/migrations/20170802000001-add-digitable-line-to-boleto.js, src/resources/boleto/model.ts, test/unit/resources/boleto/model.js
=> fix: add digitable_line to boleto

src/database/migrations/20170807000001-add-payer-address-to-boleto.js, src/providers/bradesco/index.ts, src/resources/boleto/model.ts, src/resources/boleto/schema.ts, test/functional/boleto/index.js, test/helpers/boleto/index.js, test/unit/resources/boleto/model.js
- The address field is a JSON field
- Add hook beforeValidate
- In Validation if all the required fields exist in the request of the `payer_address`
they will be maintained otherwise a default will be use
- Removed address default value to send the provider
- Always will use the `payer_address` saved at database
closes pagarme/superbowleto#236
1. I feel comfortable with the code I …
=> feature: payer address

src/providers/bradesco/index.ts
Log only body of external requests.
=> logs: hide request headers on logs

src/providers/index.ts, test/unit/providers/index.js
=> Fix provider error

src/providers/bradesco/index.ts
Remove http headers from error logs generated by axios.
=> provider: remove headers from error logs

src/lib/errors/index.ts, test/unit/lib/errors/index.js
InternalServerError was being set with the wrong prototype.
Before it was DatabaseError, now it is InternalServerError.
=> errors: fix prototype of InternalServerError

README.md
=> readme: update pagarme logo

src/resources/boleto/service.ts
Set to pending_registration boletos that failed to be
registered.
=> register: set to pending_registration boletos that failed to be registered

src/resources/boleto/service.ts
Add a bigger timeout on development/test mode.
=> service: check environment to set the timeout

src/providers/bradesco/index.ts
Remove unnecessary informations from error logs. Keep just the response
data.
=> provider: fix error logs

README.md
This PR was opened for fixing the uri link to Babel.
=> readme: add babel uri to description

src/functions/database/index.ts, src/lib/credentials/index.ts, src/providers/bradesco/index.ts, src/providers/development/index.ts, src/resources/boleto/index.ts, src/resources/boleto/service.ts
Logging the whole err object is unnecessary and would break when trying to convert it to JSON (as it is a circular JSON structure).
=> logs: do not log raw error on errors

package.json, src/bin/server.js
Add `express` as a dependency on package.json and
create a simple app with a single route on root.
Add express dependency on `package.json`.
Create simple express server/app.
Add command `npm run dev` to run the server.
this closes …
=> server: create express app

src/providers/bradesco/response-codes.ts
Since Bradesco updated their documentation, we shall update our response codes.
=> bradesco: update response codes

Dockerfile, Makefile, README.md, docker-compose.yml, package.json, script/setup
Create a service to run the application for development.
Also updates version of `eslint-plugin-import`.
this closes https://github.com/pagarme/ghostbusters/issues/7
=> docker: create development environment

package.json, src/bin/server.js, src/lib/errors/index.js, src/lib/http/response.js, src/resources/boleto/index.js, src/resources/index.js, test/functional/boleto/index.js, test/functional/boleto/show.js, test/functional/boleto/update.js, test/helpers/normalizer.js, test/unit/lib/http/response.js
Adapt lambda handlers which were used as
routes to work on the express web server.
Add default handlers for the `/boletos` resource and
add a default handler for any other routes and methods.
This closes https://github.com/pagarme/ghostbusters/issues/10 (internal issue)
In a good pull request, …
=> routes: add boleto routes to express app

src/config/database.js, src/database/index.js, src/functions/database/index.js, src/lib/credentials/index.js, src/resources/boleto/service.js, test/functional/boleto/index.js, test/helpers/boleto/index.js, test/unit/lib/errors/database.js
Add the database password to config/database. This will allow the
application not to rely on credstash to get this sensitive information.
Remove the database password from lib/credentials and fix every place
that called database.getModel or database.getDatabase.
This closes https://github.com/pagarme/ghostbusters/issues/12 (internal)
1. I feel comfortable with the code I wrote, and …
=> config: add password to database config

src/bin/server.js, src/lib/credentials/index.js, src/lib/errors/index.js, src/middlewares/authentication.js, test/functional/boletos/authentication.js, test/functional/boletos/create.js, test/functional/boletos/index.js, test/functional/boletos/show.js, test/functional/boletos/update.js, test/helpers/normalizer.js, test/unit/middlewares/authorization.js
Add authentication middleware to /boletos that
verifies a api key on the request headers.
=> routes: add authentication middleware to /boletos

src/bin/server.js, src/functions/database/index.js, src/server/shutdown.js, test/unit/functions/database/index.js
Start web-server only when database is connected, otherwise
finish the process.
this closes https://github.com/pagarme/ghostbusters/issues/56
=> web-server: start only after database is connected

Makefile, docker-compose.yml, src/bin/worker.js, src/resources/boleto/index.js, src/resources/boleto/service.js
Creates worker that register boletos which should be registered and for some reason (like the provider being offline) weren't.
this closes https://github.com/pagarme/ghostbusters/issues/9
=> Create worker that process background boleto queue

Dockerfile.server, Dockerfile.worker
Change base images to pagarme/docker-nodejs:8.9. Fix problem with
node_gyp during docker build add g++, python and make. Reduce size of
image multi-stage build feature from docker.
This closes https://github.com/pagarme/ghostbusters/issues/137
In a good pull request, everything above is true …
=> docker: add pagarme-node and env configuration

.env.example, .travis.yml, Dockerfile, Dockerfile.server, Dockerfile.worker, docker-compose.yml, package.json, script/deploy.sh, script/start_server.sh, script/start_worker.sh, src/bin/server.js, src/bin/worker.js, src/database/index.js, src/middlewares/redirect-http.js, src/server/index.js
Cria continous integration e continous deployment. O arquivo travis descreve o pipeline de deploy e o script deploy.sh realiza o deployment na stack shatterdome.
=> Cria continous integration e continous deployment

.env.example, src/bin/worker.js, src/lib/credentials/index.js, src/resources/boleto/service.js
This closes https://github.com/pagarme/ghostbusters/issues/146
=> chore: apply some changes for staging

.env.example, newrelic.js, package.json, src/bin/server.js, src/bin/worker.js, src/lib/instrumentation/index.js
Add newrelic file and configuration.
This relates to https://github.com/pagarme/ghostbusters/issues/147
=> instrumentation: add newrelic

src/lib/logger/index.js
This change makes possible differentiation between
the two versions of the superbowleto in our log tool.
Reference: https://github.com/pagarme/ghostbusters/issues/148
=> logger: change service name

src/lib/logger/index.js, src/providers/bradesco/index.js, src/server/index.js
This is releasing these changes:
#284 
#285 
#286 
=> Release v0.2.2

src/providers/bradesco/temp.js, test/unit/providers/bradesco/temp.js
The Bradesco provider will be offline on a new specific
date.
=> service: change date range of down time fallback

src/resources/boleto/service.js
This is an emergency PR to make it stop throwing timeout errors due a third party service.
=> 🚨  Change timeout from 6 seconds to 10 seconds 🚨 

src/database/migrations/20190211000001-add-index-token-to-boleto.js, src/database/migrations/20190211000002-add-index-title_id-to-boleto.js, src/resources/boleto/model.js
Create an index to `token` and `title_id` on Boletos.
=> boleto: add index to token and title_id

src/providers/bradesco/index.js, test/unit/providers/bradesco/index.js
Check the length of document_number to set the correct document_type.
=> bradesco: fix document_type when registering

src/resources/boleto/service.js
Change Bradesco request timeout to 6s.
=> bradesco: change request timeout to 6s

src/providers/bradesco/response-codes.js
Add 93005126 as a refused status code.
=> bradesco: add response code

src/providers/bradesco/brazilian-states.js
Add a new entry for `parana` matching `pr`.
=> Brazilian states map

src/database/migrations/20190213000002-add-interest-to-boleto.js, src/database/migrations/20190213000003-add-fine-to-boleto.js, src/providers/bradesco/index.js, src/resources/boleto/model.js, src/resources/boleto/schema.js, test/functional/boletos/create.js, test/helpers/boleto/index.js, test/integration/boleto/create/bradesco/pending.js, test/integration/boleto/create/bradesco/refused.js, test/integration/boleto/create/bradesco/registered.js, test/integration/boleto/create/development/pending.js, test/integration/boleto/create/development/refused.js, test/integration/boleto/create/development/registered.js, test/unit/providers/bradesco/index.js
Create fine and interest interface and send it to bradesco.
=> boleto: add fine and interest

package.json
Bump lib node-boleto to version 2.1.1
=> chore: bump node-boleto

src/providers/bradesco/index.js, src/resources/boleto/service.js
This PR adds timeout on axios request instead of set it up with bluebird.
=> register: fix timeout on request

.circleci/config.yml, src/lib/instrumentation/index.js, src/providers/bradesco/index.js, src/resources/boleto/model.js
Esse PR tem como objetivo atualizar o projeto para ser compatível com a nova infra do Superbowleto que é dividida entre `stg`, `sdx` e `prd`.
=> Superbowleto infra v4

.env.example, src/config/providers.js, src/providers/boleto-api-caixa/formatter.js, src/providers/boleto-api-caixa/index.js, src/providers/index.js, src/resources/boleto/model.js, src/resources/boleto/schema.js, src/resources/configuration/schema.js, test/functional/boletos/create.js, test/functional/configuration/create.js, test/functional/configuration/update.js, test/integration/boleto/create/boleto-api-caixa/refused.js, test/integration/boleto/create/boleto-api-caixa/registered.js, test/integration/configuration/create.js, test/integration/configuration/update.js, test/unit/providers/boleto-api-caixa/formatter.js, test/unit/providers/boleto-api-caixa/index.js
Adiciona um novo provider, o `boleto-api-caixa`, que irá registrar boletos na caixa através da boleto-api da Mundipagg.
Relates to [GHOST-29](https://mundipagg.atlassian.net/browse/GHOST-29)
=> providers: add new integration boleto-api-caixa

.circleci/config.yml, .gitignore, Makefile, README.md, package.json, sonar-project.properties
This PR includes sonar analysis step and xml test result report.
Relates to [QA-55](https://mundipagg.atlassian.net/browse/QA-55?atlOrigin=eyJpIjoiNzU4NjU1OWFlZTY4NGQyNGJmOWNhZWZlYmY2MmYxN2UiLCJwIjoiaiJ9)
You can see the test results [here](https://app.circleci.com/pipelines/github/pagarme/superbowleto/187/workflows/28a94eb8-412f-4a21-89df-12bfd5ec76cb/jobs/481/tests) and Sonar Analysis [here](https://gandalf.stone.com.br/dashboard?id=pagarme-superbowleto).
=> [QA-55] CI: include sonar analysis in workflow 

Makefile
Fix branch parameter in Sonar execution. Sonar needs to run per branch and the env used was wrong, this PR will update with the right env.
=> Fix: change branch env at Sonar execution to the right one

.circleci/config.yml, src/lib/helpers/configurations.js, test/unit/lib/helper/configurations.js
Inclui condição para que se o issuer for development, ou seja, um boleto no ambiente de teste, não altere os dados de registro para não registrar o boleto de verdade.
=> setBoletoRulesConfiguration: includes issuer development case

sonar-project.properties
Inclusão de propriedade para usar o sonarcloud
=> QA-93: Sonar Migration

.circleci/config.yml
Removendo a funcionalidade de [DLC do CI](https://circleci.com/docs/2.0/docker-layer-caching/#section=projects), ele não apresenta tantas vantagens em termos de ganho de tempo, em relação ao custo :+1: 
=> QA-113: Remove DLC feature

src/lib/helpers/configurations.js, src/resources/boleto/service.js, test/integration/lib/helper/configurations.js, test/unit/lib/helper/configurations.js
Adiciona logs nas funções que podem alterar os dados de registro do boleto, para deixar marcado nos logs que foi mudado algo da transação.
relates to https://mundipagg.atlassian.net/browse/PGHOST-75
=> findBoletoRulesConfiguration: add logs

src/database/migrations/20201103000000-add-boleto-url.js, src/providers/boleto-api-caixa/index.js, src/resources/boleto/model.js, src/resources/boleto/service.js, test/integration/boleto/create/boleto-api-caixa/registered.js, test/unit/providers/boleto-api-caixa/index.js
Para utilizar o boleto renderizado da Mundipagg, precisamos recuperar e salvar a url do boleto no Superbowleto. Assim feito, utilizaremos essa url na API do Core para renderizar o html para nossos clientes.
relates to https://mundipagg.atlassian.net/browse/PGHOST-90
=> boleto-api-caixa: render boleto

package.json, src/lib/http/request.js, src/providers/bradesco/index.js, src/resources/boleto/index.js, test/functional/boletos/index.js, test/integration/boleto/create/boleto-api-bradesco-shopfacil/registered.js, test/unit/lib/http/request.js, test/unit/providers/bradesco/index.js
PRs:
https://github.com/pagarme/superbowleto/pull/354
&
https://github.com/pagarme/superbowleto/pull/352
=> Release train 2020 12 01

docker-compose.yml, package.json, src/lib/helpers/providers.js, src/providers/boleto-api-caixa/index.js, test/integration/boleto/create/boleto-api-caixa/refused.js, test/integration/boleto/create/boleto-api-caixa/registered.js, test/unit/lib/helper/providers.js, test/unit/providers/boleto-api-caixa/index.js
Hoje quando a super boleto recebe uma requisição de emissão de boleto caixa com juros e multa, alteramos o emissor para Bradesco, onde o boleto é emitido pelo banco Bradesco. 
A partir desse PR, temos a implementação de emissão de boletos com juros e multa no projeto super boleto, para o provedor Caixa, no qual vamos mandar o request para a boleto-api, contendo os dados de juros e multa. 
Os Cases de teste estão nesse [Card](https://mundipagg.atlassian.net/browse/BPROC-390)
=> [BPROC-390] - implements interest and fine to provider Caixa

src/providers/boleto-api-caixa/index.js, test/unit/providers/boleto-api-caixa/index.js
Este PR tem como finalidade melhorar a instrução do boleto retirando o ponto que tem no final do link da página de consulta da pagarme.
Os clientes estavam copiando o link com o ponto e isso gerava uma página de not found:
Com a alteração realizada não terá mais esse ponto, assim os clientes vão copiar o link puro:
Nenhum impacto esperado na aplicação
Foi editado os testes de integração que cobrem as alterações realizadas nesse PR, validando os retornos da função de busca da instrução. Além disso todos os demais testes continuaram passando corretamente:
1. My commits are well written and follow …
=> [BPROC-535] Improves boleto instruction

src/providers/boleto-api-caixa/index.js, test/unit/providers/boleto-api-caixa/index.js
Este PR altera o campo maxDaysToPayPastDue para 0. Este campo é utilizado para configurar o praz de baixa da CEF via boleto-api.
**Monitoramento**
[Logs do worker](https://app.datadoghq.com/logs?query=service%3Asuperbowleto%20%40aws.awslogs.logGroup%3A%22%2Ffargate%2Fservice%2Fsuperbowleto-w-prd%22&cols=service%2C%40data.message.metadata.request.body.boleto.nosso_numero%2C%40data.message.metadata.boleto.title_id%2C%40data.message.metadata.item.boleto_id%2C%40data.message.metadata.boleto.payer_name%2C%40data.message.metadata.response.status.mensagem%2C%40data.message.metadata.response.boleto.nosso_numero%2C%40data.message.metadata.boleto.status%2C%40data.message.metadata.boleto.external_id%2C%40data.message.metadata.boleto.id%2C%40data.message.metadata.boleto.issuer%2C%40data.message.metada …
=> Alterar prazo de baixa CEF maxDaysToPayPastDue para 0

.circleci/config.yml, .github/workflows/lint_tests_and_sonar.yml, Makefile, README.md, package-lock.json
The purpose of this PR is to migrate the CI tool from Circle CI to Github Actions (Lint, Test and Sonar). Remove these steps from Circleci, Makefile and adjust the Required. Sonar badges will also be added in the README.
Observation:
The goal at this point is to convert to CI pipes only.
CD will be added for later due to credentials to make CD.
1. I feel comfortable with the code I …
=> QA-2477 Migrate ci to ga

catalog-info.yaml
Esse PR tem como intuito adicionar as informações do sistema da superbowleto no BackStage, definindo seus componentes e recursos, bem como dependências.
2. My commits are well written and follow [pagarme/git-style-guide](https://github.com/pagarme/git-style-guide)
3. My changes are well covered by **tests** and **logs**
4. I've updated the project docs (if needed)
5. I fell safe about this implementation
6. I feel comfortable with the code I wrote, and I'm not ashamed to show it to my friends
=> [BPROC-860] Adicionar catalog-info para o backstage

catalog-info.yaml
Esse PR realiza ajustes no conteúdo do catalog, deixando de acordo com a documentação, para todos os recursos voltarem à funcionar.
=> fix: adjust catalog content

catalog-info.yaml
=> fix: adjusts catolog content

catalog-info.yaml
=> fix: adjusts catalog content

.github/workflows/lint_tests_and_sonar.yml, package-lock.json, package.json, src/resources/boleto/schema.js, test/functional/boletos/create.js, test/unit/resources/boleto/schema.js
Esse PR tem a finalidade de remover a limitação de data de vencimento do boleto bradesco e shopfacil!
[[BPROC-1846]](https://mundipagg.atlassian.net/browse/BPROC-1846?atlOrigin=eyJpIjoiY2IwZTczNDg5NzU1NDNlY2FkYWVjYWUxZjQzMDA1MGUiLCJwIjoiaiJ9)
[BPROC-1846]: https://mundipagg.atlassian.net/browse/BPROC-1846?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BPROC-1846] Remove o limitador de data para vencimento de boleto bradesco e shopfacil

.github/workflows/lint_tests_and_sonar.yml, package-lock.json, package.json, src/resources/boleto/schema.js, test/functional/boletos/create.js, test/unit/resources/boleto/schema.js
Reverts pagarme/superbowleto#402
=> Revert "[BPROC-1846] Remove o limitador de data para vencimento de boleto bradesco e shopfacil"
