- src/providers/bradesco/index.ts
- test/unit/providers/bradesco/index.js
Change bradesco provider wallet to 26 instead of 25.
This PR can only be merged on Monday 31/07/2017.
> bradesco: change wallet to 26

- src/resources/boleto/index.ts
We were using 'and' in a situation that we should use 'both'.
> ramda: should use 'both', not 'and'

- src/providers/bradesco/index.ts
Fix a problem with the translateResponseCode function of bradesco
provider. Previously it would print "[Object object]" on logs. Now,
it prints the full object.
> bradesco: fix translate-response-code logs

- src/resources/boleto/model.ts
- test/unit/resources/boleto/model.js
Previously, the model would only check if the payer_address had all the
required fields. Add a verification to check if any of the values are
null. If any value from payer_address is null, the defaultAddress should
be used.
> model: fix boleto beforeValidate hook to normalize payer_address

- src/providers/bradesco/index.ts
- src/providers/bradesco/response-codes.ts
Fix verify status function by passing `title_id` instead of `issuer_id` and update bradesco respons-codes.
> bradesco: fix verify status function

- docker-compose.yml
Remove port binding to host on docker-compose containers. This would
make Travis fail the builds as the 5432 port is already in use.
> travis: fix cibuild ports

- src/resources/boleto/service.ts
Add a timeout of 10 seconds for the register function to execute. After
this send the boleto to background registering.
> service: add timeout for register function

- src/resources/boleto/index.ts
- src/resources/boleto/service.ts
Use the queue processor to process the sqs messages and register
boletos instead of the old way of spawning `register-boleto` lambdas for
each message at the queue.
> background-registering: process boleto on queue processor

- src/functions/database/index.ts
- src/providers/bradesco/index.ts
- src/providers/development/index.ts
- src/resources/boleto/index.ts
- src/resources/boleto/service.ts
- test/functional/boleto/create/bradesco/pending.js
- test/functional/boleto/create/bradesco/refused.js
- test/functional/boleto/processBoletosToRegister/registered.js
- test/functional/boleto/register/pending.js
- test/functional/boleto/register/refused.js
- test/helpers/normalizer.js
- test/integration/providers/bradesco/index.js
Connect all actions with the same requestId on logs. We now accept a `x-request-id` header on `/POST /boletos` that we're going to use to keep track of a given request.
> logs: refactor logs to connect all actions with the same request_id

- src/providers/bradesco/index.ts
- test/unit/providers/bradesco/index.js
We are now using the current moment as Bradesco's `data_emissao` parameter instead of boleto's created_at property. We're doing this to avoid errors with boletos that are created at one day and sent to register in another day. E.g. a boleto created at `23:59:59` on day 1 will be sent to register on `00:00:00` on day 2. Because bradesco only consider the date in a `YYYY-MM-DD` format, this would fail.
closes https://github.com/pagarme/ghostbusters/issues/85
1. I've …
> bradesco: use now() as bradesco's data_emissao parameter

- src/database/migrations/20171107000001-add-issuer-response-code-to-boleto.js
- src/providers/bradesco/index.ts
- src/resources/boleto/model.ts
- src/resources/boleto/service.ts
- test/functional/boleto/create/bradesco/pending.js
- test/functional/boleto/create/bradesco/refused.js
- test/functional/boleto/create/bradesco/registered.js
Since Bradesco send us a response with a code when trying to register a
boleto, we'll save this code in the model to query boletos by
issuer-response-code.
Closes https://github.com/pagarme/ghostbusters/issues/5
> boleto: add 'issuer-response-code' field

- package.json
Update `nyc` package version to stop printing this
`(node:58) Warning: process.on(SIGPROF) is reserved while debugging`
to the console when running tests.
> chore: bump nyc version to remove warning

- src/bin/server.js
- src/server/index.js
- src/server/shutdown.js
- test/unit/server/shutdown.js
Every time the server receives from the OS one of these
signals (SIGHUP, SIGINT, SIGTERM) it will stop receiving
requests and it will finish to serve all requests that were being
processes at the moment. After all that, the process will stop as
the OS requested.
In a good pull request, …
> web-server: add graceful shutdown

- src/providers/bradesco/index.js
Before the term used was requestId, but now it is
operationId, this should've been changed before so
it is a fix.
this closes https://github.com/pagarme/ghostbusters/issues/171
> bradesco: fix usage of operationId

- src/server/index.js
This PR implements the `/robots.txt` route, that always returns `User-Agent: * Disallow: /`. This is needed so Google and other search engines don't crawl our boletos and routes.
Closes pagarme/ghostbusters#170
> web-server: add robots.txt route

- Makefile
- docker-compose.yml
This PR basically removes the responsability of the `Makefile` to choose which script to run and it delegates to a new service on the `docker-compose.yml` file.
> docker: make migration a service on docker-compose

- src/providers/bradesco/temp.js
- src/resources/boleto/service.js
- test/unit/providers/bradesco/temp.js
The Bradesco provider will be offline on a specific
date. Add fake register logic to cover this period so
that all boletos sent will be registered later.
Co-authored-by: thor99 <thor.garcia@pagar.me>
Co-authored-by: lucianopf <luciano.franca@pagar.me>
In a good pull request, everything above is …
> service: cover bradesco down time on register

- package.json
- src/lib/instrumentation/index.js
Add `dd-trace` library to send APM metrics to Datadog's platform.
This will not remove the existing instrumentation tool (newrelic) to provide a smooth transition in the near future.
> datadog: add dd-trace lib

- src/providers/bradesco/index.js
- test/unit/providers/bradesco/index.js
This PR aims to allow us to define the desired issuer_wallet when its manually provided.
PS: I would love to use `propOr` since we're talking about a single prop instead of `pathOr`, but it seems that there's a bug at Ramda at the current version we're using at Superbowleto.
Here are 2 screenshots either with the newest version and with the current version
> Wallet: Setup issuer_wallet

- src/bin/server.js
- src/bin/worker.js
- src/config/index.js
- src/lib/bootstrap/index.js
- src/lib/instrumentation/index.js
Add configuration options to dd-trace library, the default value for the hostname is `localhost` which in this case will be the Datadog agent's load balancer endpoint, the default port is also 8126, I just decided to leave it explicit within the application :) 
In a good pull request, …
> Add configuration option to dd-trace library

- src/server/index.js
Change default timeout value to avoid 5XX errors. These errors
were generated because our ELB idle timeout is longer than the express
default timeout.
> server: increase default timeout value

- src/lib/instrumentation/index.js
Remove config options from dd-trace library since we will be using another strategy (described in the commit message) to send information to Datadog's agent.
> Remove Datadog config options

- src/server/index.js
Change default headersTimeout value to avoid 5XX errors. These errors
were generated because our ELB idle timeout is longer than the express
default headersTimeout.
> server: increase headers timeout value

- src/lib/helpers/providers.js
- src/resources/boleto/service.js
- test/unit/lib/helper/providers.js
Dado que a `boleto-api` não suporta registro utilizando informação de juros e multa, precisamos trocar o `issuer` pra `bradesco` quando chegar uma requisição nesse cenário: `issuer: boleto-api-bradesco-shopfacil` e `interest` (juros) ou `fine` (multa) preenchidos.
Relates to https://mundipagg.atlassian.net/browse/GHOST-17
> boleto: change issuer when boleto-api and interest/fine info

- src/lib/helpers/providers.js
- src/resources/boleto/service.js
- test/unit/lib/helper/providers.js
Verificamos que o log de [`change_issuer`](https://github.com/pagarme/superbowleto/blob/master/src/lib/helpers/providers.js#L29) não estava sendo agrupado junto aos outros logs dos boletos. Para corrigir isso, é necessário passar o `operationId` do fluxo padrão para a função, e instanciar o log passando o `operationId`
Relates to GHOST-28
> change_issuer: add operationId to log

- docker-compose.yml
- package.json
- src/database/migrations/20200709000000-add-external-id-to-boleto.js
- src/database/migrations/20200804000000-add-rules-to-boleto.js
- src/database/seeders/20200707213655-configuration.js
- src/lib/helpers/configurations.js
- src/resources/boleto/model.js
- src/resources/boleto/schema.js
- src/resources/boleto/service.js
- test/functional/configuration/authentication.js
- test/functional/configuration/create.js
- test/functional/configuration/show.js
- test/functional/configuration/update.js
- test/integration/boleto/create.js
- test/integration/boleto/create/boleto-api-bradesco-shopfacil/pending.js
- test/integration/boleto/create/boleto-api-bradesco-shopfacil/refused.js
- test/integration/boleto/create/boleto-api-bradesco-shopfacil/registered.js
- test/integration/boleto/create/development/pending.js
- test/integration/boleto/create/development/refused.js
- test/integration/boleto/create/development/registered.js
- test/integration/configuration/create.js
- test/integration/configuration/show.js
- test/integration/configuration/update.js
- test/integration/lib/helper/configurations.js
- test/unit/lib/helper/configurations.js
Este PR visa tirar algumas responsabilidades do [boleto-processor](https://github.com/pagarme/pagarme-core/blob/master/gateway/lib/environments/pagarme/boleto-processor.js) do gateway e inserir uma nova lógica ao superbowleto.
Segue as etapas que foram adicionadas ao chegar uma requisição:
- verificar se a requisição chegou com `boleto.rules` preenchido, se sim deve-se considerar a carteira de acordo com a regra escolhida. (isso atualmente é feito no [boleto-processor](https://github.com/pagarme/pagarme-core/blob/25251eea560f58d9d70c35a779123684a03f44a7/gateway/lib/environments/pagarme/boleto-processor.js#L61), mas mudamos para o superbowleto)
- caso não tenha `boleto.rules` devemos buscar as configurações de registro daquela company na model de …
> Configuration: add logic to find boleto config

- src/providers/bradesco/index.js
- test/unit/providers/bradesco/index.js
Conforme relatado em thread do Slack interno, estávamos tendo alguns problemas na função `normalizePercentage`, quando chegavam alguns valores "peculiares".
Exemplo, se chegasse o valor `0.07` pra função, o retorno da mesma seria `7000.000000000001`. Com o uso do `parseInt` na cadeia de `pipe`, temos como retorno `00007000`, o valor esperado.
> normalize-percentage: use parseInt to deal with certain cases

- package.json
- src/lib/http/request.js
- src/resources/boleto/index.js
- test/functional/boletos/index.js
- test/integration/boleto/create/boleto-api-bradesco-shopfacil/registered.js
- test/unit/lib/http/request.js
Analisando algumas requests com erro no DataDog, identificamos que, no caso das requisições get realizadas no endpoint `/boletos/:id` alguns erros estão ocorrendo devido ao envio de parâmetros query desconhecidos, ou seja, parâmetros que não estão no schema de validação `indexSchema` do Joi.
[Logs do caso em questão](https://app.datadoghq.com/logs?cols=%40latency%2Chost%2C%40body.error.message%2C%40data.message.metadata.status%2C%40body.amount&event&from_ts=1609182920697&index=&live=false&messageDisplay=inline&query=trace_id%3A3250228666586175386&stream_sort=desc&to_ts=1609184920724)
A ideia é permitir que esses parâmetros desconhecidos sejam passados na request adicionando a opção `allowUnknown` na função Joi.validate, dessa forma eles serão ignorados pois não são utilizados e a request …
> Add allow unknown get parameters

- src/providers/boleto-api-caixa/index.js
- src/resources/boleto/service.js
- test/integration/boleto/create/boleto-api-caixa/registered.js
- test/unit/providers/boleto-api-caixa/index.js
Atualmente ainda estamos usando o node-boleto para criar a linha digitável dos boletos da caixa, mas isso está errado, pois o node-boleto não sabe lidar com essa informação para o banco caixa. Então devemos recuperar essa informação da resposta da boleto-api e enviar corretamente para o gateway para que fique tudo certo no banco de dados do Core.
relates to  https://mundipagg.atlassian.net/browse/PGHOST-143
> boleto-api-caixa: enviar barcode e digitable line para o gateway

- script/start.sh
- src/database/migrations/20201208134000-drop-index-title-id-in-boleto.js
- src/database/migrations/20201208134100-create-index-title-id-to-boleto.js
- src/database/migrations/20201208134130-drop-index-token-in-boleto.js
- src/database/migrations/20201208134200-create-index-token-to-boleto.js
Com o problema que tivemos no deploy da renderização do boleto caixa, foi verificado que havia dois indíces com problemas no db do Superbowleto. Por isso, vamos removê-los e criá-los de novamente.
> boleto index: drop and create again

- src/providers/boleto-api-caixa/index.js
- test/unit/providers/boleto-api-caixa/index.js
Assim como nos boletos renderizados do Bradesco o nome do beneficiário aparece : "nome da company | Pagar.me Pagamentos S/A", precisamos que o mesmo aconteça nos boletos da Caixa.
Como, no caso da Caixa, usamos a renderização que o próprio banco retorna, é necessário incluir a parte da pagarme na request que enviamos para a boleto-api e caixa, assim o boleto renderizado terá todas as informações para o campo de beneficiário.
relates to https://mundipagg.atlassian.net/browse/PGHOST-160
> boleto-caixa: includes pagarme in recipient name

- src/providers/boleto-api-caixa/index.js
- test/unit/providers/boleto-api-caixa/index.js
Adiciona os dados corretos da agência para registro na Caixa, para corrigir, uma vez que as requests chegam com os dados do bradesco que estão chumbados no gateway.
> boleto-api-caixa: add the correct agency to payload

- src/providers/boleto-api-caixa/formatter.js
- src/providers/boleto-api-caixa/index.js
- test/unit/providers/boleto-api-caixa/formatter.js
- test/unit/providers/boleto-api-caixa/index.js
Ao tentar registrar boletos de outras companies na Caixa, descobrimos que a Caixa utiliza apenas os dados do beneficiário(Pagar.me) para o registro dos boletos e não possui o campo sacador avalista(company), então precisamos manter fixo o cnpj da pagarme para o registro ocorrer com sucesso.
> boleto-api-caixa: add pagarme cnpj

- src/lib/helpers/providers.js
- test/unit/lib/helper/providers.js
A função `changeIssuerWhenInterestOrFine` que lida com boletos que possuem juros e multa no Superbowleto, está alterando apenas o issuer para ser registrado diretamente pelo Bradesco, mas precisamos alterar também a conta, agência e carteira nestes casos, pois usamos essas informações para renderizar o boleto depois. 
Atualmente quando um boleto que seria registrado pela boleto-api-caixa entra nessa condição, corremos o risco de renderizar um código de barras que não dá para ser pago, por conter as informações de agência e conta da caixa.
relates to https://mundipagg.atlassian.net/browse/PGHOST-178
> boleto: change register when have interest/fine

- .circleci/config.yml
- src/lib/helpers/configurations.js
- src/providers/boleto-api-caixa/index.js
- test/unit/lib/helper/configurations.js
- test/unit/providers/boleto-api-caixa/index.js
Esta modificação tem por objetivo remover a funcionalidade que força a virada para emissor Bradesco caso o cliente envie o nó `boleto_rules` ou se o mesmo tiver configurado na company a `issuer_wallet = 26`. A virada para o Bradesco era necessária porque a BoletoAPI não aceitava regras menos restritivas de pagamento (baixa em D+n e pagamento divergente do valor do título). Com a implementação da v2 na BoletoAPI, a mesma passará a receber tais informações e a virada para o Bradesco deixará de ser obrigatória. Evidências dos testes no card da tarefa.
relates to : [BPROC-98](https://mundipagg.atlassian.net/browse/BPROC-98)
> boleto-api-caixa : envia boleto rules para boleto-api

- src/providers/boleto-api-caixa/formatter.js
- src/providers/boleto-api-caixa/index.js
- test/unit/providers/boleto-api-caixa/formatter.js
- test/unit/providers/boleto-api-caixa/index.js
Após adição do campo sacador avalista no request da boleto-api, o campo do sacador avalista deve ser adicionado no request da superbowleto para a boleto-api. Este PR adiciona o campo sacador avalista (payeeGuarantor) no request da caixa.
In a good pull request, everything above is true …
> [BPROC-402] - Adição de campo sacador avalista no request da caixa da superbowleto para a boleto-api

- src/lib/helpers/providers.js
- test/integration/boleto/create/boleto-api-caixa/refused.js
- test/integration/boleto/create/boleto-api-caixa/registered.js
- test/unit/lib/helper/providers.js
Em continuação ao PR [BPROC-390 - implements interest and fine to provider Caixa](https://github.com/pagarme/superbowleto/pull/369), esse PR tem o objetivo de remover a trava abrindo o registro de boletos caixa com juros e multa pela a BoletoAPI para todas as companies.
> [BPROC-390] - opens the Boleto Caixa lock with interest and fine for BoletoAPI

- src/providers/boleto-api-caixa/index.js
- src/resources/boleto/model.js
- test/unit/providers/boleto-api-caixa/index.js
Este PR remove o campo endereço do buyer no request para a boleto-api quando o endereço é substituído pelo endereço do pagarme ou for o mesmo da company.
> [BPROC-418]-Remove buyer address when address is equal to pagarme or company

- src/providers/boleto-api-caixa/index.js
Atualmente, a superbowleto espera por 10s a resposta da boleto-api na integração com a Caixa para o registro de boletos. Após esse tempo, a superbowleto corta a conexão e salva o status do boleto como refused, assumindo que o boleto não foi registrado. Ocorreu alguns casos em que a boleto-api registrou o boleto após a conexão ser rompida, em um tempo médio de 16s, o que gera uma inconsistência entre as duas aplicações. 
Este PR visa aumentar o tempo de espera de 10s para 20s, o que, em tese, irá reduzir a quantidade de ocorrências desse tipo.
2. My commits are well written and follow …
> [BPROC-679] Adjust timeout with Caixa integration

- src/resources/boleto/schema.js
- test/unit/resources/boleto/schema.js
Aplicado sanitização no campo `payer_name` que estava causando  a falha no registro do boleto Bradesco.
> [BPROC-321] Falha no registro do boleto com caracteres especiais

- src/resources/boleto/schema.js
- test/functional/boletos/create.js
- test/unit/resources/boleto/schema.js
O intuito desse PR é remover a trava de limitação de data de expiração para o issuer de development. Além disso, corrige a data limite para o fim do dia 22-02-2025, às 23h59, ao invés de para o início do dia (00h). 
2. My commits are well written and follow [pagarme/git-style-guide](https://github.com/pagarme/git-style-guide)
3. My changes are well covered by **tests** and **logs**
4. I've updated the project docs (if needed)
5. I fell safe about this implementation
6. I feel comfortable with the code I wrote, and I'm not ashamed to show it to my friends
> BPROC-819 - Remover limitação de data de expiração para o issuer development

- src/bin/server.js
- src/server/index.js
Hoje em algumas requisições entre o pagarme-gateway e a superbowleto, temos um erro onde o pagarme-gateway recebe erro 502 conforme podemos ver nessa [query](https://app.datadoghq.com/logs?query=service%3Apagarme-gateway%20%40metadata.statusCode%3A5%2A%20Superbowleto%20error%20for%20transaction%20%40dd.env%3Aproduction%20&cols=host%2Cservice&index=%2A&messageDisplay=inline&stream_sort=desc&viz=stream&from_ts=1687219042536&to_ts=1688515042536&live=true). Há um tempo atrás tínhamos esse problema também na aplicação PIX, onde a configuração de Keep Alive Timeout estava incorreta no webserver do PIX e com isso fazia com que o servidor encerrasse uma conexão, e posteriormente o client tentava usar essa conexão já encerrada, e recebia o erro 502.
- Corrige a configuração do keep Alive timeout
- …
> [BPROC-1285] Ajustar Keep Alive Timeout e Headers Timeout

- catalog-info.yaml
Esse PR realiza ajustes no conteúdo do catalog, deixando de acordo com a documentação, para todos os recursos voltarem à funcionar.
> fix: adjust catalog content
